### ISSUE TITLE
Hang on network issue

### ISSUE THREAD

**Issue by 24v** [Juniper/netconf-java#12] opened 2016-04-19 17:22 UTC
We've noticed that the library will hang indefinitely sometimes when the connection to the router is lost (like from a reboot).  Here is the stacktrace:

"(job)" #80 daemon prio=5 os_prio=0 tid=0x00007f4078073000 nid=0x171 in Object.wait() [0x00007f407e5e7000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at ch.ethz.ssh2.StreamGobbler.read(StreamGobbler.java:231)
        - locked <0x00000000e5f2d830> (a java.lang.Object)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        - locked <0x00000000e5f9ac78> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        - locked <0x00000000e5f9ac78> (a java.io.InputStreamReader)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at net.juniper.netconf.NetconfSession.getRpcReply(NetconfSession.java:86)
        at net.juniper.netconf.NetconfSession.closeConfiguration(NetconfSession.java:879)
        at net.juniper.netconf.Device.closeConfiguration(Device.java:1056)
       ....

"Thread-115565" #148604 daemon prio=5 os_prio=0 tid=0x00007f40782f8800 nid=0x5f1c in Object.wait() [0x00007f407d9e0000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at ch.ethz.ssh2.channel.ChannelManager.getChannelData(ChannelManager.java:981)
        - locked <0x00000000e5f25bb0> (a ch.ethz.ssh2.channel.Channel)
        at ch.ethz.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:64)
        at ch.ethz.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:77)
        at ch.ethz.ssh2.StreamGobbler$GobblerThread.run(StreamGobbler.java:51)

"Thread-115564" #148603 daemon prio=5 os_prio=0 tid=0x00007f40782ab000 nid=0x5f1b runnable [0x00007f407dce1000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:150)
        at java.net.SocketInputStream.read(SocketInputStream.java:121)
        at ch.ethz.ssh2.crypto.cipher.CipherInputStream.fill_buffer(CipherInputStream.java:45)
        at ch.ethz.ssh2.crypto.cipher.CipherInputStream.internal_read(CipherInputStream.java:58)
        at ch.ethz.ssh2.crypto.cipher.CipherInputStream.getBlock(CipherInputStream.java:87)
        at ch.ethz.ssh2.crypto.cipher.CipherInputStream.read(CipherInputStream.java:119)
        at ch.ethz.ssh2.transport.TransportConnection.receiveMessage(TransportConnection.java:234)
        at ch.ethz.ssh2.transport.TransportManager.receiveLoop(TransportManager.java:839)
        at ch.ethz.ssh2.transport.TransportManager$1.run(TransportManager.java:510)
        at java.lang.Thread.run(Thread.java:745)

**Comment by pasvorn** [comment] 2016-04-19 22:09
I notice your choice of wording - "the library will hang indefinitely sometimes when the connection to the router is lost (like from a reboot)". I assume that this means that you did 
device.connect()
{ 
  do a bunch of processing
  router reboot
  but the Java thread is still active
  router came backup, but now send TCP reset because ssh session is no longer valid
 Session hang indefinitely
}

I did a simple testing and I get a different result from your testing.
In my test, I had a loop that get query from a router, in the middle of the loop, I disconnect my VPN which cut my session off from my router. About a minute later, my thread exit with Fatal Error.

[Fatal Error] :1:1: Premature end of file.
Exception in thread "main" org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Premature end of file.
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:257)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:348)
	at net.juniper.netconf.NetconfSession.convertToXML(NetconfSession.java:69)
	at net.juniper.netconf.NetconfSession.executeRPC(NetconfSession.java:226)
	at net.juniper.netconf.Device.executeRPC(Device.java:530)
	at ShowInterface.main(ShowInterface.java:44)

I will do some more testing to see if I can see similar "hang" session.

**Comment by ChrisJenn** [comment] 2016-04-20 02:40
Can you share your code, so we can attempt to reproduce the behaviour?

**Comment by leodream** [comment] 2016-08-29 09:31
```
"Thread-115565" #148604 daemon prio=5 os_prio=0 tid=0x00007f40782f8800 nid=0x5f1c in Object.wait() [0x00007f407d9e0000]
java.lang.Thread.State: WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:502)
at ch.ethz.ssh2.channel.ChannelManager.getChannelData(ChannelManager.java:981)
- locked <0x00000000e5f25bb0> (a ch.ethz.ssh2.channel.Channel)
at ch.ethz.ssh2.channel.ChannelInputStream.read(ChannelInputStream.java:64)
```
Maybe it has run into the issue here -- http://www.ganymed.ethz.ch/ssh2/FAQ.html#blocking

In SSH-2 protocol, **stderr** and **stdout** share the same receive window, which may block you to read one stream when the windows is full with another stream's data.
The recommended way is to use two worker threads that consume remote stdout and stderr **in parallel**.

**Comment by peterjhill** [comment] 2017-02-10 01:30
yes... it is exactly that... not consuming the stderr and it getting filled up

**Comment by peterjhill** [comment] 2019-06-20 16:56
This should be fixed in https://github.com/Juniper/netconf-java/pull/21
I wired in a different ssh library. When both the channels and sessions are created I pass in a value for timeouts (they are independent timeouts).

In the new major version, it uses the builder pattern to create new devices. It should not be hard to update the version. in Examples/CreateDevice, it shows different ways to create a new device. To change the timeout, you would add .timeout(<int value milliseconds>) in the build chain.

**Closed** 2019-07-02 06:22 UTC
